name: battery-notifier
version: '0.1.0'
summary: Battery Notifier
description: |
  An app that notifies you when a device battery reaches 20 or 80 percent.
base: core22
confinement: strict
grade: devel
compression: lzo

apps:
  battery-notifier:
    command: electron/battery-notifier --no-sandbox
    extensions: [gnome]
    plugs:
      - browser-support
      - network
      - network-bind
      - upower-observe
    environment:
      # Correct the TMPDIR path for Chromium Framework/Electron to ensure
      # libappindicator has readable resources.
      TMPDIR: $XDG_RUNTIME_DIR

parts:
  battery-notifer:
    plugin: dump
    source: .
    override-build: |
      npx electron-packager release/app battery-notifier --overwrite --platform=linux --output=release/build --prune=true --out=$SNAPCRAFT_PART_INSTALL/
      mv $SNAPCRAFT_PART_INSTALL/battery-notifier-linux-* $SNAPCRAFT_PART_INSTALL/electron

      snapcraftctl build

      chmod -R 755 $SNAPCRAFT_PART_INSTALL
    build-snaps:
      - node/18/stable

  upower:
    plugin: nil
    stage-packages: [ upower ]
