name: battery-notifier
version: '0.2.0'
summary: Battery Notifier
description: |
  An app that notifies you when a device battery reaches 20 or 80 percent.
base: core22
confinement: strict
grade: stable
compression: lzo

apps:
  battery-notifier:
    command: battery-notifier-linux-x64/battery-notifier --no-sandbox
    extensions: [gnome]
    plugs:
      - browser-support
      - network
      - network-bind
      - unity7
      - upower-observe
    environment:
      # Correct the TMPDIR path for Chromium Framework/Electron to ensure
      # libappindicator has readable resources.
      TMPDIR: $XDG_RUNTIME_DIR

parts:
  battery-notifier:
    plugin: dump
    source: ./electron
    override-build: |
      pwd
      ls -la $SNAPCRAFT_PART_INSTALL
      npx @electron/packager ./release/app battery-notifier --overwrite --platform=linux --prune=true --out=$SNAPCRAFT_PART_INSTALL/
      ls -la $SNAPCRAFT_PART_INSTALL
      mkdir $SNAPCRAFT_PART_INSTALL/battery-notifier-linux-x64/resources/assets
      cp -r ./assets $SNAPCRAFT_PART_INSTALL/battery-notifier-linux-x64/resources || exit

      ls -la $SNAPCRAFT_PART_INSTALL
      chmod -R 755 $SNAPCRAFT_PART_INSTALL
      ls -la $SNAPCRAFT_PART_INSTALL
    build-snaps:
      - node/18/stable

  upower:
    plugin: nil
    stage-packages: [ upower ]
