name: battery-notifier
base: core20
version: '0.1.0'
summary: Notifies you when a device battery is too low or too high.
description: |
  You know what? This app is amazing! It does all the things
  for you. Some say it keeps you young, maybe even happy.

grade: stable
confinement: classic

parts:
  app:
    plugin: dump
    source: release/build/linux-unpacked
    source-type: local
    stage-packages:
      - libasound2
      - libnotify4
      - libnspr4
      - libnss3
      - libpcre3
      - libpulse0
      - libxss1
      - libxtst6

apps:
  batteryNotifier:
    command: battery-notifier
    desktop: battery-notifier.desktop
    # Correct the TMPDIR path for Chromium Framework/Electron to ensure
    # libappindicator has readable resources.
    environment:
      TMPDIR: $XDG_RUNTIME_DIR
