name: battery-notifier  # Replace with your snap name, use lowercase and no spaces
base: core20          # The base snap is the execution environment for your app
version: '0.1.0'        # Version of your snap
summary: An app that notifies you when a device battery reaches 20 or 80 percent.
description: |
  An app that notifies you when a device battery reaches 20 or 80 percent.

grade: devel  # Must be 'stable' to release into candidate/stable channels
confinement: devmode  # Use 'strict' to enforce security but may need additional configurations

parts:
  your-part-name:
    plugin: dump
    source: ./release/build
    source-type: local
    organize:
      'Battery Notifier-0.1.0.AppImage': app/BatteryNotifier.AppImage
  fuse:
    plugin: nil
    stage-packages:
      - libfuse2
      - fuse

apps:
  battery-notifier:  # Name of your app command, replace this
    command: app/BatteryNotifier.AppImage
    plugs: [home, x11, unity7, wayland, pulseaudio, network, network-bind, fuse-support]

